<div id='body-accueil'>
	<section id='presentation-accueil'>
		<p id="expertise">Une expertise à votre service !</p>
		<h3><a href='#presentation-accueil'><i class="fas fa-sort-down"></i></a></h3>
		<p>Maxime Eripel vous propose ses services à domicile pour toutes coupes, colorations, soins du cheveux, femme, homme et enfants.</p>		
		<p>N'hésitez pas à le <a href='demande.php'><span>contacter</span></a> pour toute demande d'information, devis, que se soit pour votre quotidien, pour un relloking ou un évènement.</p>
	</section> 
	<div id='slider-accueil'>
		<section id='slideA'>
			<img src='img/photo4.jpeg' class='active'>
			<img src='img/photo6.jpeg'>
		</section>
		<section id='slideB'>
			<img src='img/photo5.jpeg' class='active'>
			<img src="img/photo7.png">
		</section>	
	</div>
	<section id='presentation'>
		<p id='citation'>« La Coiffure est en constante évolution, il y aura toujours quelque chose à créer mais aussi à apprendre… »</p>
		<p>Après un bac littéraire et quelques semaines passées sur les bancs de la fac en cinéma, Maxime s’ennuie et souhaite trouver une voie plus propice à l’expression concrète de sa créativité débordante. Il cherche ce métier qui lui permettrait d’allier son sens naturel de l’humain, sa soif d’apprendre et sa quête de la Beauté dans notre monde.</p>
		<p>C’est ainsi que Maxime, la tête pleine de l’esthétique de ses romans favoris du XVIIIème  siècle, découvre, un peu sur le tard, la coiffure. C’est une révélation pour lui et la passion, le prend au corps et au cœur dès le début.</p>
		<p>Ses goûts littéraires et cinématographiques lui font porter un intérêt tout particulier à l’art du chignon et à la coiffure à travers les âges. Il aime ainsi jouer avec les styles et les techniques afin de revisiter les grands classiques avec raffinement et modernité. </p>
		<p>Son insatiable curiosité l’a mené à toucher à tout, que ce soit en coloration, coiffage, coupe dame et homme mais aussi le rasage à l’ancienne. Autant de qualifications qu’il met aujourd’hui à votre service.</p>
		<p>Depuis 2013, à l’instar d’Edward aux mains d’argent, brosses, peignes et ciseaux sont autant d’extensions de ses bras…</p>
	</section>
	<h3 style='text-align: center;'><a href='accueil.php'><i class="fas fa-caret-up"></i></a></h3>
</div>