<div id='tarifs'>
	<Table>
		<tr>
			<th><h2>TARIFS FEMMES</h2></th>
			<th style='padding: 2%;'>Court</th>
			<th style='padding: 2%;'>Mi-long</th>
			<th style='padding: 2%;'>Long</th>
		</tr>
		<tr>
			<td>Shampoing Brush</td>
			<td class='td-center'>17€</td>
			<td class='td-center' class='td-center'>22€</td>
			<td class='td-center'>26€</td>
		</tr>
		<tr>
			<td>Shampoing Coupe Brush</td>
			<td class='td-center'>22€</td>
			<td class='td-center'>26€</td>
			<td class='td-center'>32€</td>
		</tr>
		<tr>
			<td>Shampoing Couleur (racines) Brush</td>
			<td class='td-center'>30€</td>
			<td class='td-center'>35€</td>
			<td class='td-center'>40€</td>
		</tr>
		<tr>
			<td>Shampoing Couleur (complète) Brush</td>
			<td class='td-center'>35€</td>
			<td class='td-center'>40€</td>
			<td class='td-center'>45€</td>
		</tr>
		<tr>
			<td>Shampoing Couleur (racines) / Coupe Brush</td>
			<td class='td-center'>45€</td>
			<td class='td-center'>50€</td>
			<td class='td-center'>55€</td>
		</tr>
		<tr>
			<td>Shampoing Balayage / Mèches Brush</td>
			<td class='td-center'>45€</td>
			<td class='td-center'>52€</td>
			<td class='td-center'>60€</td>
		</tr>						
	</Table>			
	<table style='margin-top: 5%;'>
		<tr>
			<th><h2>TARIFS HOMME</h2></th>
			<th></th>
		</tr>
		<tr>
			<td>Coupe</td>
			<td class='td-center'>15€</td>
		</tr>
		<tr>
			<td>Barbe</td>
			<td class='td-center'>8€</td>
		</tr>
	</table>
	<table style='margin-top:5%;'>
		<tr>
			<th colspan="2"><h2>AUTRES TARIFS</h2></th>
		</tr>
		<tr>
			<th>Soins</th>
			<th></th>
		</tr>
		<tr>
			<td >Soin léger</td>
			<td class='td-center'>3€</td>
		</tr>
		<tr>
			<td>Soin profond</td>
			<td class='td-center'>6€</td>
		</tr>
		<tr>
			<td>Soin Mulato</td>
			<td class='td-center'>8€</td>
		</tr>
		<tr>
			<th>Couleurs</th>
			<th></th>
		</tr>
		<tr>
			<td>Patine</td>
			<td class='td-center'>15€</td>
		</tr>
		<tr>
			<td>Coup de soleil</td>
			<td class='td-center'>15€</td>
		</tr>
		<tr>
			<td>Décoloration</td>
			<td class='td-center'>25€</td>
		</tr>
		<tr>
			<td>Shampoing Américain</td>
			<td class='td-center'>15€</td>
		</tr>
		<tr>
			<td>Dose supplémentaire Couleur</td>
			<td class='td-center'>5€</td>
		</tr>
		<tr>
			<th>Evènements</th>
			<th></th>
		</tr>			
		<tr>
			<td>Forfait mariée</td>
			<td class='td-center'>60€</td>
		</tr>
		<tr>
			<td>Essai</td>
			<td class='td-center'>15€</td>
		</tr>
		<tr>
			<td>Chignon soirée</td>
			<td class='td-center'>35€</td>
		</tr>
		<tr>
			<td>Tresse</td>
			<td class='td-center'>à partir de 15€ (devis selon prestation)</td>
		</tr>
	</table>	 
	<p>Pour toute information supllémentaire, veuillez me contacter <a href='demande.php' style='color: rgb(50,82,82);'>ici</a>.</p>
</div>
	<h3 style='text-align: center;'><a href='tarifs.php'><i class="fas fa-caret-up"></i></a></h3>